module.exports = {
  "bodyFont": "Roboto",
  "themeData": {
    "--primary-color": "#0a6e35",
    "--second-color": "#07a125",
    "--dark-color": "#000000",
    "--grey-color": "#E2E2E2",
    "--alert-color": "#E63946",
    "--app-bg-color": "#F9F9F9",
    "--Acent-color": "#FFFFFF",
    "--sidebar-bg-color": "#1c1c1c",
    "--sidebar-menu-bg": "#1c1c1c",
    "--sidebar-menu-color": "#FFFFFF",
    "--sidebar-menu-hover-bg": "#0a6e35",
    "--sidebar-menu-active-bg": "#07a125",
    "--sidebar-menu-icon-color": "#FFFFFF",
    "--sidebar-menu-icon-hover-color": "#FFFFFF",
    "--sidebar-menu-icon-active-color": "#FFFFFF",
    "--sidebar-menu-border-radius": "16px",
    "--sidebar-top-right-radius": "18px",
    "--sidebar-bottom-right-radius": "18px",
    "--scroll-color": "#0a6e35",
    "--header-bg-color": "#FFFFFF",
    "--header-icon-color": "#FFFFFF",
    "--header-icon-hover-color": "#0a6e35",
    "--header-icon-bg": "#1c1c1c",
    "--header-icon-hover-bg": "#111111",
    "--card-body-bg-color": "#1c1c1c",
    "--card-body-font-color": "#FFFFFF",
    "--card-title-font-color": "#f9f9f9",
    "--card-dec-font-color": "#fdfdfd",
    "--card-footer-bg-color": "#2a2d2b",
    "--card-footer-font-color": "#c7b2b2",
    "--top-nav-menu-bg": "#000000",
    "--top-nav-menu-hover-bg": "#111111",
    "--top-nav-menu-active-bg": "#111111",
    "--top-nav-menu-color": "#FFFFFF",
    "--top-nav-menu-hover-color": "#0a6e35",
    "--top-nav-menu-active-color": "#07a125",
    "--card-header-gradient-start": "#1c1c1c",
    "--card-header-bg-gradient": "linear-gradient(90deg, #1c1c1c 0%, #1c1c1c 100%)",
    "--card-header-gradient-end": "#1c1c1c",
    "--card-body-border-color": "#E2E2E2",
    "--bg-gradient": "linear-gradient(38deg, rgba(0,0,0,0.95) 45%, rgba(37,175,96,1) 55%)",
    "--sidebar-main-bg-gradient": "#1c1c1c",
    "--login-card-bg-gradient": "#000",
    "--login-link-text-color": "#0a6e35",
    "--login-button-bg-gradient": "#00c853",
    "--login-button-bg-color": "#0a6e35",
    "--login-card-bg-color": "#1c1c1c",
    "--header-main-bg-gradient": "linear-gradient(90deg, #ffffff 0%, #ffffff 100%)",
    "--header-icon-hover": "#0a6e35",
    "--scroll-width": "7px",
    "--card-title-font-size": "18px",
    "--card-body-border-radius": "24px",
    "--lockedMenus": "{}",
    "--body-font": "Roboto",
    "--login-bg-gradient": "linear-gradient(135deg, #0E0E0E 0%, #1A1A1A 50%, #2B2B2B 100%)",
    "--login-card-width": "480px",
    "--login-card-border-radius": "22px",
    "--login-card-box-shadow": "0 8px 30px rgba(0, 0, 0, 0.4)",
    "--login-input-border-color": "#333333",
    "--login-input-bg-color": "#0E0E0E",
    "--login-input-text-color": "#FFFFFF",
    "--login-input-border-radius": "10px",
    "--login-button-border-radius": "4px",
    "--login-button-text-color": "#ffffff",
    "--login-button-hover-bg-color": "#00e676",
    "--login-button-hover-text-color": "#0E0E0E",
    "--login-footer-text-color": "#BFA76B",
    "--login-logo-space": "50px",
    "--login-layout-padding-right": "8%",
    "--login-company-logo": "url('https://msgsndr-private.storage.googleapis.com/companyPhotos/47b7e157-d197-4ce5-9a94-b697c258702a.png')",
    "--login-logo-width": "140px",
    "--login-logo-height": "70px",
    "--login-logo-filter": "drop-shadow(0 2px 6px rgba(212,175,55,0.3))",
    "--login-background-active": "linear-gradient(90deg, #000000 0%, #000000 100%)",
    "--sidebar-bg-end-color": "#0ab6ff",
    "--login-background-gradient-start": "#f00505",
    "--login-background-gradient-end": "#ffea00",
    "--login-card-bg-gradient-start": "#049521",
    "--login-card-bg-gradient-end": "#049521",
    "--login-button-gradient-start": "#049521",
    "--login-button-gradient-end": "#000000",
    "--login-button-text": "\"Get In\"",
    "--login-link-text-size": "14px",
    "--forgetpassword-text": "\"FORGOT\"",
    "--login-headline-font-size": "38px",
    "--login-headline-text-color": "#00c853",
    "--login-headline-text": "\"WELCOME\"",
    "--header-gradient-start": "#1a1a1a",
    "--header-gradient-end": "#2a2a2a",
    "--loader-background-color": "#1c1c1c",
    "help-icon-color": "#ffffff",
    "help-icon-hover": "#eeeeee",
    "help-bg-color": "#188bf6",
    "help-bg-hover": "#146cc0",
    "profile-icon-color": "#ffffff",
    "profile-icon-hover": "#ffffff",
    "profile-bg-color": "#146c0e",
    "profile-bg-hover": "#000000",
    "--agency-logo": "url(\"https://msgsndr-private.storage.googleapis.com/companyPhotos/47b7e157-d197-4ce5-9a94-b697c258702a.png\")",
    "--agency-logo-url": "https://msgsndr-private.storage.googleapis.com/companyPhotos/47b7e157-d197-4ce5-9a94-b697c258702a.png",
    "--logo-height": "80px",
    "--header-gradient-stop": "0%",
    "--header-gradient-angle": "90deg",
    "--loader-mode": "loaders",
    "--hiddenMenus": "{\"sb_launchpad\":{\"hidden\":false,\"display\":\"flex !important\",\"toggleChecked\":false},\"sb_dashboard\":{\"hidden\":false,\"display\":\"flex !important\",\"toggleChecked\":false},\"sb_email-marketing\":{\"hidden\":false,\"display\":\"flex !important\",\"toggleChecked\":false}}",
    "--sidebarTitles": "{\"--sb_agency-dashboard-new-name\":\"Agency Dashboard\",\"--agency-dashboard-new-name\":\"Agency Dashboard\",\"--launchpad-new-name\":\"Launchpad\",\"--conversations-new-name\":\"Conversations\",\"--dashboard-new-name\":\"Dashboard\"}",
    "--logo-width": "80px",
    "--custom-pointer": "url(\"https://theme-builder-delta.vercel.app/images/skybluenew-pointer.png\") 0 0, pointer",
    "--custom-cursor": "url(\"https://theme-builder-delta.vercel.app/images/gradientborder-cursor.png\") 0 0",
    "--menuCustomizations": "{\"sb_dashboard\":{\"title\":\"Dashboard\",\"icon\":\"f853\"},\"sb_conversations\":{\"title\":\"Conversations\",\"icon\":\"f27a\"},\"sb_calendars\":{\"title\":\"Calendars\",\"icon\":\"f133\"},\"sb_launchpad\":{\"title\":\"Launchpad\",\"icon\":\"f06a\"},\"sb_opportunities\":{\"title\":\"Opportunities\",\"icon\":\"f83e\"},\"sb_contacts\":{\"title\":\"Contacts\",\"icon\":\"f2c2\"},\"sb_payments\":{\"title\":\"Payments\",\"icon\":\"f81d\"},\"sb_reporting\":{\"title\":\"Reporting\",\"icon\":\"f24d\"},\"sb_email-marketing\":{\"title\":\"Email Marketing\",\"icon\":\"f07a\"},\"sb_automation\":{\"title\":\"Automation\",\"icon\":\"f544\"},\"sb_sites\":{\"title\":\"Sites\",\"icon\":\"f0ac\"},\"sb_app-media\":{\"title\":\"App Media\",\"icon\":\"f478\"},\"sb_memberships\":{\"title\":\"Memberships\",\"icon\":\"f390\"},\"sb_reputation\":{\"title\":\"Reputation\",\"icon\":\"f005\"}}",
    "--login-background-image": "url('https://images.unsplash.com/photo-1504384308090-c894fdcc538d')",
    "--agencyMenuOrder": "",
    "--bg-gradient-start": "#ffffff",
    "--bg-gradient-end": "#ffffff",
    "--subMenuOrder": "[\"sb_launchpad\",\"sb_dashboard\",\"sb_conversations\",\"sb_calendars\",\"sb_opportunities\",\"sb_contacts\",\"sb_payments\",\"sb_reporting\",\"sb_email-marketing\",\"sb_automation\",\"sb_sites\",\"sb_app-media\",\"sb_memberships\",\"sb_reputation\"]",
    "--themebuildermaincolor": "#0a6e35",
    "--themebuildermain-active-bg": "#07a125",
    "--sidebar-text-hover-color": "#ffffff",
    "--sidebar-text-active-color": "#ffffff",
    "--card-header-bg-color": "212121",
    "--tw-text-opacity": "#FFFFFF",
    "--tw-text-opacity-color": "#FFFFFF",
    "--loader-css": "{\"_id\":\"68f7d22d0aa198636134e675\",\"isActive\":true}",
    "--loader-color-rgb": "255, 255, 255",
    "--go-back-color": "#000000",
    "--go-back-text-color": "#ffffff",
    "--custom-logo-url": "",
    "--custom-logo-css": "",
    "--theme-mode": "dark"
  },
  "selectedTheme": "Default Theme",
}